// <auto-generated />
namespace ShaulisBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcreationdatetoFan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcreationdatetoFan));
        
        string IMigrationMetadata.Id
        {
            get { return "201611081223108_added creation date to Fan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
